version: "3.8"
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - $PWD/STORAGE/pm:/data
      - $PWD/STORAGE/letsencrypt:/etc/letsencrypt
    networks:
      - ujere_net
  database:
    image: mongo:latest
    restart: always
    container_name: 'mongodb'
    ports:
        - 27017:27017
    volumes:
      - $PWD/STORAGE/mongodb:/data/db
    networks:
        - ujere_net
  user:
    restart: always
    build: ./user
    depends_on:
      - database
    container_name: 'userAuth'
    volumes:
     - $PWD/STORAGE/uploads:/app/uploads
    environment:
      PORT: "${PORT}"
      MONGODB_HOST: "${MONGODB_HOST}"
    networks:
        - ujere_net
  form:
    restart: always
    build: ./forms
    depends_on:
      - database
    volumes:
     - $PWD/STORAGE/uploads:/app/uploads
    container_name: 'forms'
    environment:
      PORT: "${PORT}"
      MONGODB_HOST: "${MONGODB_HOST}"
    networks:
        - ujere_net
  web:
    restart: always
    build: ./web
    depends_on:
      - database
    container_name: 'web'
    networks:
        - ujere_net
networks:
  ujere_net:
    driver: bridge
