services:
  web:
    build: ./forntend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.abnaibi-web-route.rule=Host(`cv.ddldlabs.com.ng`)
      - traefik.http.routers.abnaibi-web-route.tls=true
      - traefik.http.routers.abnaibi-web-route.tls.certresolver=myresolver
      - traefik.http.routers.abnaibi-web-route.middlewares=https-redirect@docker
      - traefik.http.services.abnaibi.loadbalancer.server.port=80
      - traefik.http.routers.abnaibi-web-http-to-https.rule=Host(`cv.ddldlabs.com.ng`)
      - traefik.http.routers.abnaibi-web-http-to-https.entrypoints=web
      - traefik.http.routers.abnaibi-web-http-to-https.middlewares=https-redirect
    networks:
      - ddld-net
  api:
    restart: always
    build: ./backend
    volumes:
     - $PWD/STORAGE/uploads:/app/src/uploads
    environment:
      APP_PORT: "${APP_PORT}"
      MONGO_URI: "${MONGO_URI}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.abnaibi-web-route.rule=Host(`api.cv.ddldlabs.com.ng`)
      - traefik.http.routers.abnaibi-web-route.tls=true
      - traefik.http.routers.abnaibi-web-route.tls.certresolver=myresolver
      - traefik.http.routers.abnaibi-web-route.middlewares=https-redirect@docker
      - traefik.http.services.abnaibi.loadbalancer.server.port=3000
      - traefik.http.routers.abnaibi-web-http-to-https.rule=Host(`api.cv.ddldlabs.com.ng`)
      - traefik.http.routers.abnaibi-web-http-to-https.entrypoints=web
      - traefik.http.routers.abnaibi-web-http-to-https.middlewares=https-redirect
    networks:
      - ddld-net
networks:
  ujere_net:
    driver: bridge
