version: "3.8"
services:
  reverse-proxy:
    restart: always
    image: traefik:v2.4
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=false"
      - "--providers.docker=true"
      - "--log.LEVEL=DEBUG"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--traefik.frontend.rule=Host:ddld.info,www.ddld.info"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=umar.jere@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
        - ujere_net         
  database:
    image: mongo:5.0
    restart: always
    container_name: 'mongodb'
    ports:
        - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
        - ujere_net        
  user:
    restart: always
    build: ./user
    labels:
      - traefik.port=3000
      - traefik.enable=true
      - traefik.docker.network=ujere_net
    depends_on:
      - database  
    container_name: 'userAuth'
    networks:
        - ujere_net   
  form:
    restart: always
    build: ./forms
    labels:
      - traefik.port=3000
      - traefik.enable=true
      - traefik.docker.network=ujere_net
    depends_on:
      - database  
    volumes:
     - ${PWD}/uploads:/app/uploads  
    container_name: 'forms'
    networks:
        - ujere_net                                                          
networks:
  ujere_net:
    driver: bridge          
volumes:
  mongodata:   