version: "3.8"
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - $PWD/STORAGE/pm:/data
      - $PWD/STORAGE/letsencrypt:/etc/letsencrypt
    networks:
      - ujere_net
  database:
    image: mongo:latest
    restart: always
    container_name: 'mongodb'
    volumes:
      - $PWD/STORAGE/mongodb:/data/db
    networks:
        - ujere_net
  api:
    restart: always
    build: ./backend
    depends_on:
      - database
    container_name: 'api'
    volumes:
     - $PWD/STORAGE/uploads:/app/uploads
    environment:
      APP_PORT: "${APP_PORT}"
      MONGO_URI: "${MONGO_URI}"
    networks:
        - ujere_net
networks:
  ujere_net:
    driver: bridge
